basePath: /api/v1
definitions:
  ports.LoginInput:
    properties:
      login_email:
        type: string
      password:
        type: string
    required:
    - login_email
    - password
    type: object
  ports.LoginResponse:
    properties:
      expires_at:
        type: string
      session_id:
        type: integer
      token:
        type: string
      token_type:
        type: string
      user:
        $ref: '#/definitions/ports.UserResponse'
    type: object
  ports.UserCreationSchema:
    properties:
      adk_session_id:
        maxLength: 128
        type: string
      contact_email:
        type: string
      contact_phone_no:
        maxLength: 20
        type: string
      first_name:
        maxLength: 60
        minLength: 2
        type: string
      last_name:
        maxLength: 60
        minLength: 2
        type: string
      login_email:
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - first_name
    - login_email
    - password
    type: object
  ports.UserResponse:
    properties:
      active:
        type: boolean
      contact_email:
        type: string
      contact_phone_no:
        type: string
      created_at:
        type: string
      email_verified:
        type: boolean
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      login_email:
        type: string
      updated_at:
        type: string
    type: object
  ports.UserUpdateSchema:
    properties:
      active:
        type: boolean
      adk_session_id:
        maxLength: 128
        type: string
      contact_email:
        type: string
      contact_phone_no:
        maxLength: 20
        type: string
      email_verified:
        type: boolean
      first_name:
        maxLength: 60
        minLength: 2
        type: string
      last_name:
        maxLength: 60
        minLength: 2
        type: string
      login_email:
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API server for the TIA platform.
  license:
    name: Apache 2.0
  title: TIA API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user with email and password, returning a JWT and
        session details.
      parameters:
      - description: User Login Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/ports.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.LoginResponse'
        "400":
          description: Validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials or deactivated account
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User Login
      tags:
      - Auth
  /auth/logout:
    post:
      description: Revokes the current user's session token.
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: User Logout
      tags:
      - Auth
  /auth/me:
    get:
      description: Retrieves the details of the currently authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.UserResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get Current User
      tags:
      - Auth
  /users:
    get:
      description: Retrieves a list of all user accounts.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ports.UserResponse'
            type: array
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Creates a new user account with the provided details.
      parameters:
      - description: User Creation Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/ports.UserCreationSchema'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ports.UserResponse'
        "400":
          description: Validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: User with email already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Password complexity error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user
      tags:
      - Users
  /users/{id}:
    delete:
      description: Deletes a user by their ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a user
      tags:
      - Users
    get:
      description: Retrieves the details of a single user by their unique ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.UserResponse'
        "400":
          description: Invalid user ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Updates a user's details by their ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User Update Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/ports.UserUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ports.UserResponse'
        "400":
          description: Invalid request body or ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
